### PR TITLE
Tasp core update

### PR DESCRIPTION
**Pull request by Petr-Eichler**
I merged `core-overview` and `tasp-libarary` sections into one and extended some parts of the text. I also excluded `optimizer-comparison` into a new section.

### CODE REVIEW

**Comment by martinbabka** [comment]
we need to check how we compare to different named products, SAP, MS something, etc. Just to mention that it is much more general. This however, could be mentioned in the presentation added by Fanda with back-link to this doc.

**Comment by martinbabka** [comment]
We should wait for Fanda's opinion here.

**Comment by martinbabka** [comment]
I am possibly missing the `optimizer-components.pdf`

**Comment by Petr-Eichler** [comment]
> we need to check how we compare to different named products, SAP, MS something, etc. Just to mention that it is much more general. This however, could be mentioned in the presentation added by Fanda with back-link to this doc.

I did not start that section yet. This pull request updates `optimizer-overview`. I am going to address the `optimizer-comparison` tomorrow.

> I am possibly missing the optimizer-components.pdf

Yeah, sorry for that, *.pdf is in .gitignore, I fixed that.

**Pull request merged**
